<script>
  import Curso from "../components/Curso.svelte";
  import Main from "../templates/main.svelte";
</script>

<svelte:head>
    <title>Cursos de especialización</title> 
</svelte:head>


<Main>
  <div class="container w-100 p-2 p-md-4 slide-in-left">
    <div class="row">
      <div class="col-xl-6">
        <Curso
          nombre="Desarrollo de videojuegos"
          imageUrl="https://images.unsplash.com/photo-1542751371-adc38448a05e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80"
          url='desarrollo-videojuegos'
          />
      </div>
      <div class="col-xl-6 mt-4 mt-xl-0">
        <Curso
          nombre="Especialización en ciberseguridad"
          imageUrl="https://images.unsplash.com/photo-1584433144859-1fc3ab64a957?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1330&q=80"
          url="ciberseguridad"
        />
      </div>
    </div>
  </div>
</Main>

<style>
  .slide-in-left {
    -webkit-animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94)
      both;
    animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2023-2-1 21:3:55
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
  @-webkit-keyframes slide-in-left {
    0% {
      -webkit-transform: translateX(-1000px);
      transform: translateX(-1000px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0);
      transform: translateX(0);
      opacity: 1;
    }
  }
  @keyframes slide-in-left {
    0% {
      -webkit-transform: translateX(-1000px);
      transform: translateX(-1000px);
      opacity: 0;
    }
    100% {
      -webkit-transform: translateX(0);
      transform: translateX(0);
      opacity: 1;
    }
  }
</style>
