<script>
  import Saos from "saos";
</script>

<div class="container-fluid col-12 text-white bg-primary">
  <div class="col-12 col-md-9 p-4">
    <Saos
      animation={"scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both"}
    >
      <h1 class="fs-2 text-decoration-underline">
        ¿Quién puede acceder a estas enseñanzas?
      </h1>
      <ol>
        <li>
          <p>
            Técnico Superior en Administración de Sistemas Informáticos en Red
            establecido por el Real Decreto 1629/2009, de 30 de octubre, por el
            que se establece el título de Técnico Superior en Administración de
            Sistemas Informáticos en Red y se fijan sus enseñanzas mínimas.
          </p>
        </li>
        <li>
          <p>
            Técnico Superior en Desarrollo de Aplicaciones Multiplataforma,
            establecido por el Real Decreto 450/2010, de 16 de abril, por el que
            se establece el título de Técnico Superior en Desarrollo de
            Aplicaciones Multiplataforma y se fijan sus enseñanzas mínimas.
          </p>
        </li>
        <li>
          <p>
            Técnico Superior en Desarrollo de Aplicaciones Web, establecido por
            el Real Decreto 686/2010, de 20 de mayo, por el que se establece el
            título de Técnico Superior en Desarrollo de Aplicaciones Web y se
            fijan sus enseñanzas mínimas.
          </p>
        </li>
        <li>
          <p>
            Técnico Superior en Sistemas de Telecomunicaciones e Informáticos,
            establecido por el Real Decreto 883/2011, de 24 de junio, por el que
            se establece el título de Técnico Superior en Sistemas de
            Telecomunicaciones e Informáticos y se fijan sus enseñanzas mínimas.
          </p>
        </li>
        <li>
          <p>
            Técnico Superior en Mantenimiento Electrónico, establecido por el
            Real Decreto 1578/2011, de 4 de noviembre, por el que se establece
            el Título de Técnico Superior en Mantenimiento Electrónico y se
            fijan sus enseñanzas mínimas.
          </p>
        </li>
      </ol>
    </Saos>
  </div>
</div>

<style>
  .container-fluid {
    margin-top: 5rem;
  }
  ol li {
    list-style-type: lower-latin;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2023-2-10 17:7:42
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
 @-webkit-keyframes -global-scale-up-center {
    0% {
      -webkit-transform: scale(0.5);
      transform: scale(0.5);
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
  }
  @keyframes -global-scale-up-center {
    0% {
      -webkit-transform: scale(0.5);
      transform: scale(0.5);
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
  }
</style>
